# This is a basic workflow to help you get started with Actions

name: Test env variables
on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
       GITHUB_REPO1: dummy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: |
          echo $GITHUB_REPO1
      - name: Change env
        run: |
          GITHUB_REPO1=new
      - name: Desplay new env
        run: |
          echo $GITHUB_REPO1
        
